### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by makruger** [nerk/asciidoctor-bs-themes#3]
Hello,

I'd really like to try your asciidoctor bootstrap themes, but I'm experiencing some errors when I try to build everything. Hoping you can help. - Michael

./buildcss 
creating css/bootstrap_default.css
/home/mike/.rvm/gems/ruby-2.3.0/gems/less-2.6.0/bin/lessc:83:in `<top (required)>': invalid option: --global-var=bsw-root='https://raw.githubusercontent.com/thomaspark/bootswatch/gh-pages' (OptionParser::InvalidOption)
        from /home/mike/.rvm/gems/ruby-2.3.0/bin/lessc:23:in `load'
        from /home/mike/.rvm/gems/ruby-2.3.0/bin/lessc:23:in `<main>'
        from /home/mike/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/mike/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
./buildcss: line 10: cleancss: command not found

**Comment by nerk** [comment]
Looks you are using the Ruby version of 'less' rather than the Node.js version. Seems they are not really compatible. You need to install:

npm install -g less
npm install -g request
npm install -g clean-css 

Make sure that the node.js version of less is found first on your path or uninstall the corresponding Ruby gem. Also make sure you've got the 'Asciidoctor', 'tilt', and 'coderay' gems.

I just tried to build it in my environment and it works. However, it's been a while that I used this project and it might well be that there are problems because of changes to Bootstrap etc. Good luck!

**Comment by makruger** [comment]
Thank you for pointing me in the right direction. I was indeed using the Ruby version of less, etc. Also ran into a little snag where the build script could not find node.

/usr/bin/env: node: No such file or directory

After Googling the error I was able to resolve it by installing nodejs-legacy. Apparently on Debian, node is delivered as nodejs. The legacy version fixes that. So, everything looks to be working now. Table #2 looks like it has a small issue, but everything else looks fine. Thank you for your help.

**Comment by nerk** [comment]
Glad it works for you.
